name: github_client
description: Um cliente GitHub em Flutter
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  github: ^9.4.0
  fluttericon: ^2.0.0
  url_launcher: ^6.1.4
  oauth2: ^2.0.5
  window_to_front: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
